# fly.toml app configuration file generated for golang-insiders-com on 2023-11-14T20:46:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "golang-insiders-com"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ["app"]
